### PR TITLE
Update the pubsub image to one that works on M1 processors

### PR DESCRIPTION
**Pull request by jensljungblad**
Updates the pubsub emulator to an image that works on M1 processors.

### CODE REVIEW

**Comment by Linuus** [comment]
I did a `docker-compose up` and got:

```sh
#9 25.84 Fetching grpc 1.42.0
#9 26.24 Installing grpc 1.42.0 with native extensions
#9 120.8 Killed
------
executor failed running [/bin/sh -c bundle install]: exit code: 137
ERROR: Service 'worker' failed to build : Build failed
```

**Comment by Linuus** [comment]
If running `docker-compose up pubsub`:

```sh
❯ docker-compose up pubsub
Creating kisi-api-challenge_pubsub_1 ... done
Attaching to kisi-api-challenge_pubsub_1
pubsub_1  | Executing: /google-cloud-sdk/platform/pubsub-emulator/bin/cloud-pubsub-emulator --host=0.0.0.0 --port=8681
pubsub_1  | [pubsub] This is the Google Pub/Sub fake.
pubsub_1  | [pubsub] Implementation may be incomplete or differ from the real system.
pubsub_1  | [pubsub] May 13, 2022 8:13:25 AM com.google.cloud.pubsub.testing.v1.Main main
pubsub_1  | [pubsub] INFO: IAM integration is disabled. IAM policy methods and ACL checks are not supported
pubsub_1  | [pubsub] May 13, 2022 8:13:28 AM io.gapi.emulators.netty.NettyUtil applyJava7LongHostnameWorkaround
pubsub_1  | [pubsub] INFO: Applied Java 7 long hostname workaround.
pubsub_1  | [pubsub] May 13, 2022 8:13:29 AM com.google.cloud.pubsub.testing.v1.Main main
pubsub_1  | [pubsub] INFO: Server started, listening on 8681
pubsub_1  | Usage: env PUBSUB_PROJECT1="project1,topic1,topic2:subscription1" /usr/bin/pubsubc
pubsub_1  |   -debug
pubsub_1  |     	Enable debug logging
pubsub_1  |   -help
pubsub_1  |     	Display usage information
pubsub_1  |   -version
pubsub_1  |     	Display version information
pubsub_1  | [pubsub] May 13, 2022 8:13:30 AM io.gapi.emulators.grpc.GrpcServer$3 operationComplete
pubsub_1  | [pubsub] INFO: Adding handler(s) to newly registered Channel.
```

**Comment by olssonr** [comment]
> If running `docker-compose up pubsub`:
> 
> ```shell
> ❯ docker-compose up pubsub
> Creating kisi-api-challenge_pubsub_1 ... done
> Attaching to kisi-api-challenge_pubsub_1
> pubsub_1  | Executing: /google-cloud-sdk/platform/pubsub-emulator/bin/cloud-pubsub-emulator --host=0.0.0.0 --port=8681
> pubsub_1  | [pubsub] This is the Google Pub/Sub fake.
> pubsub_1  | [pubsub] Implementation may be incomplete or differ from the real system.
> pubsub_1  | [pubsub] May 13, 2022 8:13:25 AM com.google.cloud.pubsub.testing.v1.Main main
> pubsub_1  | [pubsub] INFO: IAM integration is disabled. IAM policy methods and ACL checks are not supported
> pubsub_1  | [pubsub] May 13, 2022 8:13:28 AM io.gapi.emulators.netty.NettyUtil applyJava7LongHostnameWorkaround
> pubsub_1  | [pubsub] INFO: Applied Java 7 long hostname workaround.
> pubsub_1  | [pubsub] May 13, 2022 8:13:29 AM com.google.cloud.pubsub.testing.v1.Main main
> pubsub_1  | [pubsub] INFO: Server started, listening on 8681
> pubsub_1  | Usage: env PUBSUB_PROJECT1="project1,topic1,topic2:subscription1" /usr/bin/pubsubc
> pubsub_1  |   -debug
> pubsub_1  |     	Enable debug logging
> pubsub_1  |   -help
> pubsub_1  |     	Display usage information
> pubsub_1  |   -version
> pubsub_1  |     	Display version information
> pubsub_1  | [pubsub] May 13, 2022 8:13:30 AM io.gapi.emulators.grpc.GrpcServer$3 operationComplete
> pubsub_1  | [pubsub] INFO: Adding handler(s) to newly registered Channel.
> ```

ah nice, this looks like pubsub service starts correctly at least! this is what did not work for Jens before

**Comment by olssonr** [comment]
> I did a `docker-compose up` and got:
> 
> ```shell
> #9 25.84 Fetching grpc 1.42.0
> #9 26.24 Installing grpc 1.42.0 with native extensions
> #9 120.8 Killed
> ------
> executor failed running [/bin/sh -c bundle install]: exit code: 137
> ERROR: Service 'worker' failed to build : Build failed
> ```

hm, but why is this failing, I'll see if I get same issue!

**Comment by olssonr** [comment]
btw, I just realized that the web server exits when I run docker compose up, says another web server is already running @jensljungblad is it supposed to work out of the box?

**Comment by Linuus** [comment]
> I just run on my M1 and it all worked for me! Although I ran on Docker 4.6.1, trying now with 4.8.1
> 
> @Linuus could you comment out line 7 in Dockerfile (the bundle install command) and then run `docker compose run worker /bin/bash` and then run bundle install inside the shell so we can see what error you get?

```sh
root@2440fe875fb6:/usr/src/app# bundle install
Warning: the running version of Bundler (2.1.4) is older than the version that created the lockfile (2.2.33). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.2.33`.
Fetching gem metadata from https://rubygems.org/.........
Fetching rake 13.0.6
Installing rake 13.0.6
Fetching concurrent-ruby 1.1.9
Installing concurrent-ruby 1.1.9
Fetching i18n 1.8.11
Installing i18n 1.8.11
Fetching minitest 5.15.0
Installing minitest 5.15.0
Fetching tzinfo 2.0.4
Installing tzinfo 2.0.4
Fetching zeitwerk 2.5.3
Installing zeitwerk 2.5.3
Fetching activesupport 6.1.4.4
Installing activesupport 6.1.4.4
Fetching builder 3.2.4
Installing builder 3.2.4
Fetching erubi 1.10.0
Installing erubi 1.10.0
Fetching mini_portile2 2.7.1
Installing mini_portile2 2.7.1
Fetching racc 1.6.0
Installing racc 1.6.0 with native extensions
Fetching nokogiri 1.13.1 (aarch64-linux)
Installing nokogiri 1.13.1 (aarch64-linux)
Fetching rails-dom-testing 2.0.3
Installing rails-dom-testing 2.0.3
Fetching crass 1.0.6
Installing crass 1.0.6
Fetching loofah 2.13.0
Installing loofah 2.13.0
Fetching rails-html-sanitizer 1.4.2
Installing rails-html-sanitizer 1.4.2
Fetching actionview 6.1.4.4
Installing actionview 6.1.4.4
Fetching rack 2.2.3
Installing rack 2.2.3
Fetching rack-test 1.1.0
Installing rack-test 1.1.0
Fetching actionpack 6.1.4.4
Installing actionpack 6.1.4.4
Fetching nio4r 2.5.8
Installing nio4r 2.5.8 with native extensions
Fetching websocket-extensions 0.1.5
Installing websocket-extensions 0.1.5
Fetching websocket-driver 0.7.5
Installing websocket-driver 0.7.5 with native extensions
Fetching actioncable 6.1.4.4
Installing actioncable 6.1.4.4
Fetching globalid 1.0.0
Installing globalid 1.0.0
Fetching activejob 6.1.4.4
Installing activejob 6.1.4.4
Fetching activemodel 6.1.4.4
Installing activemodel 6.1.4.4
Fetching activerecord 6.1.4.4
Installing activerecord 6.1.4.4
Fetching marcel 1.0.2
Installing marcel 1.0.2
Fetching mini_mime 1.1.2
Installing mini_mime 1.1.2
Fetching activestorage 6.1.4.4
Installing activestorage 6.1.4.4
Fetching mail 2.7.1
Installing mail 2.7.1
Fetching actionmailbox 6.1.4.4
Installing actionmailbox 6.1.4.4
Fetching actionmailer 6.1.4.4
Installing actionmailer 6.1.4.4
Fetching actiontext 6.1.4.4
Installing actiontext 6.1.4.4
Fetching public_suffix 4.0.6
Installing public_suffix 4.0.6
Fetching addressable 2.8.0
Installing addressable 2.8.0
Fetching ast 2.4.2
Installing ast 2.4.2
Using bundler 2.1.4
Fetching byebug 11.1.3
Installing byebug 11.1.3 with native extensions
Fetching coderay 1.1.3
Installing coderay 1.1.3
Fetching faraday-em_http 1.0.0
Installing faraday-em_http 1.0.0
Fetching faraday-em_synchrony 1.0.0
Installing faraday-em_synchrony 1.0.0
Fetching faraday-excon 1.1.0
Installing faraday-excon 1.1.0
Fetching faraday-httpclient 1.0.1
Installing faraday-httpclient 1.0.1
Fetching multipart-post 2.1.1
Installing multipart-post 2.1.1
Fetching faraday-multipart 1.0.3
Installing faraday-multipart 1.0.3
Fetching faraday-net_http 1.0.1
Installing faraday-net_http 1.0.1
Fetching faraday-net_http_persistent 1.2.0
Installing faraday-net_http_persistent 1.2.0
Fetching faraday-patron 1.0.0
Installing faraday-patron 1.0.0
Fetching faraday-rack 1.0.0
Installing faraday-rack 1.0.0
Fetching faraday-retry 1.0.3
Installing faraday-retry 1.0.3
Fetching ruby2_keywords 0.0.5
Installing ruby2_keywords 0.0.5
Fetching faraday 1.9.3
Installing faraday 1.9.3
Fetching ffi 1.15.5
Installing ffi 1.15.5 with native extensions
Fetching google-protobuf 3.19.3
Installing google-protobuf 3.19.3 with native extensions
Fetching googleapis-common-protos-types 1.3.0
Installing googleapis-common-protos-types 1.3.0
Fetching grpc 1.42.0
Installing grpc 1.42.0 with native extensions
Killed
root@2440fe875fb6:/usr/src/app#
```

Not sure what happened here :D

**Comment by Linuus** [comment]
My issue was that Docker had too little memory...

**Pull request merged**
